server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .html

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=chat"
    username: postgres
    password: rclgjf

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
